name: Unzip on Push
on: push
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: beautysalonlms1 (1).zip -d extracted_files/
      - uses: actions/upload-artifact@v3
        with:
          name: extracted-files
          path: extracted_files/
